name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pingsafe/s1cnscli:latest
      options: --entrypoint ""

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        load: true # This is important to actually load the built image into Docker's environment
        tags: test:v1

    - name: Configure SentinelOne CNS CLI
      run: s1-cns-cli config --api-token $TOKEN
      env:
         TOKEN: ${{secrets.SENTINELONE_CNS_TOKEN}}

    - name: Run Vuln Scanner
      run:  s1-cns-cli --output-format SARIF --output-file vuln.sarif scan vuln --docker-image test:v1

  
